tasks:
  - init: |
      make bundle-install
    command: |
      make bundle-install

ports:
  - port: 4000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint  
    
